# Generated by Django 4.1.1 on 2022-11-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_artist_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
