# Generated by Django 4.1.1 on 2022-11-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
    ]
