# Generated by Django 4.1.1 on 2022-11-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
