# Generated by Django 4.1.1 on 2022-11-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_artist_rank_alter_artist_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='height',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='rank',
        ),
    ]
