# Generated by Django 4.1.1 on 2022-11-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_alter_artist_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
    ]
