# Generated by Django 4.1.1 on 2022-11-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0010_remove_song_release_date_song_release_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
