# Generated by Django 4.1.1 on 2022-11-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0011_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
