# Generated by Django 4.1.3 on 2022-12-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0012_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Gospel', 'Gospel'), ('Afrobeats', 'Afrobeats'), ('Rock', 'Rock'), ('House', 'House'), ('Indie Rock', 'Indie Rock'), ('Jazz', 'Jazz'), ('Hip Hop', 'Hip Hop'), ('Electro', 'Electro'), ('Soul', 'Soul'), ('Instrumental', 'Instrumental'), ('Techno', 'Techno'), ('R&B', 'R&B'), ('Pop', 'Pop'), ('Country', 'Country'), ('Garage', 'Garage'), ('Classical', 'Classical')], max_length=60),
        ),
    ]
